// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbblY-hiYf7Nl2s92pkCVn4KsiISxHHdE',
    appId: '1:408851050031:web:3172d7a1449d9d8e4a20da',
    messagingSenderId: '408851050031',
    projectId: 'flutter-course-19660',
    authDomain: 'flutter-course-19660.firebaseapp.com',
    storageBucket: 'flutter-course-19660.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa7fA4wn0x9Kxi96bh53H3yqSWMDLbWGY',
    appId: '1:408851050031:android:0022e2465de00b434a20da',
    messagingSenderId: '408851050031',
    projectId: 'flutter-course-19660',
    storageBucket: 'flutter-course-19660.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbblY-hiYf7Nl2s92pkCVn4KsiISxHHdE',
    appId: '1:408851050031:web:d0bb40f0fe652a834a20da',
    messagingSenderId: '408851050031',
    projectId: 'flutter-course-19660',
    authDomain: 'flutter-course-19660.firebaseapp.com',
    storageBucket: 'flutter-course-19660.appspot.com',
  );
}
